name: "Protocol Buffer Go Stubs Generation"
on:
  push:
    branches:
      - '*'
jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - name: "Generate for Golang"
        run: |
          sudo apt-get install -y protobuf-compiler golang-goprotobuf-dev
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          protoc --go_out=./golang --go_opt=paths=source_relative --go-grpc_out=./golang --go-grpc_opt=paths=source_relative ./**/*.proto
          cd golang
          go mod init github.com/mic-x01/grpc-microservices-in-go-proto
          go mod tidy
          git config --global user.email "m.marques.dev@gmail.com"
          git config --global user.name "mic-x01"
          git add .
          git commit -am "proto update"
          git push origin main
